module.exports = {
  title: 'KEYNOTES',
  department: 'MS Data Visualization',
  school: 'Parsons School of Design',
  location: 'zoom',
  date: '2020-05-13',
  time: '6:30PM',
  students: [
    'Mio Akasako',
    'Amanda Anderson-You',
    'Marisa Asari',
    'Xingyang Cai',
    'Zui Chen',
    'Robin Coenen',
    'Michael Desai',
    'Antonie Dreyer',
    'Daniel Grunebaum',
    'Xingwei Huang',
    'Brad MacDonald',
    'Yiran Ni',
    'Neil Oliver',
    'John Outwater',
    'Caitlyn Ralph',
    'Dan Ran',
    'Saloni Naishad Shah',
    'Lulu Tanenbaum',
    'Janice Yamanaka-Lew',
    'Nour Zein'
  ]
}
